### PR TITLE
Fix round line join on 180 degree corner

### LINKED ISSUE #8751: [bezierCurveTo] Line cap/join not applied when line segments are drawn in opposite direction
### Expected Behavior
_'it should render a line cap if a line turns by 180°'_
### Current Behavior
This behavior was issued in an earlier issue https://github.com/pixijs/pixijs/issues/8288 , which was fixed. 
But the solution didn't apply to **bezierCurveTo**
### Possible Solution
https://github.com/pixijs/pixijs/pull/8325

### Environment

- **`pixi.js` version**: _e.g. 6.5.6_
- **Browser & Version**: _e.g. Chrome 106_
- **OS & Version**: _e.g. Windows 10_
- **Running Example**: https://www.pixiplayground.com/#/edit/mr1KrSdvWUI5WR7Pk1luL

### PR DESCRIPTION
**Pull request by SuperSodaSea**
##### Description of change

Update the logic in `buildNonNativeLine` to deal with 180 degree or nearly 180 degree corners, and add some tests for it.

Fixes #8751.

Example: https://pixiplayground.com/#/edit/E97IvI759l-TZekre5v5J
- By row: `lineTo + lineTo`, `lineTo + bezierCurveTo`, `bezierCurveTo + bezierCurveTo`
- By column: `MITER`, `BEVEL`, `ROUND`

Before:
- `Math.PI` (Missing round join, wrong topology for `lineTo + lineTo`)
image
- `Math.PI + 0.001` (Missing round join for `bezierCurveTo + bezierCurveTo`)
image

After:
- `Math.PI`
image
- `Math.PI + 0.001`
image

##### Pre-Merge Checklist

- [x] Tests and/or benchmarks are included
- [x] Lint process passed (`npm run lint`)
- [x] Tests passed (`npm run test`)

### CODE REVIEW

**Review by bigtimebuddy — APPROVED** [review]
Thanks for the visuals and tests. Both make this an easy review!

File: packages/graphics/src/utils/buildLine.ts [hunk 1]
```diff
@@ -326,19 +326,56 @@ function buildNonNativeLine(graphicsData: GraphicsData, graphicsGeometry: Graphi
...
+            }
+            else
+            {
+                // 180 degree corner
+                verts.push(
+                    x1 - (perpx * innerWeight),
+                    y1 - (perpy * innerWeight));
+                verts.push(
+                    x1 + (perpx * outerWeight),
+                    y1 + (perpy * outerWeight));
```
Comment (bigtimebuddy) [inline packages/graphics/src/utils/buildLine.ts:357]: Is there a reason you didn't pull this out of the if/else? These first two points seems the same to me.

```suggestion
           verts.push(
                x1 - (perpx * innerWeight),
                y1 - (perpy * innerWeight));
            verts.push(
                x1 + (perpx * outerWeight),
                y1 + (perpy * outerWeight));

            if (dot >= 0)
            {
```

Comment (bigtimebuddy) [reply packages/graphics/src/utils/buildLine.ts]: Sorry I messed up the whitespacing ☹️

Comment (SuperSodaSea) [reply packages/graphics/src/utils/buildLine.ts]: I'm fixing it :)

**Comment by bigtimebuddy** [comment]
Thank you!
