### PR TITLE
fix: memory leaks in renderer systems

### LINKED ISSUE #11550: Bug: Memory leak regression in PIXI.Graphics (WebGL)
### Current Behavior

A memory leak occurs when a PIXI.Graphics object is repeatedly cleared and redrawn (e.g., using quadraticCurveTo). With each redraw, new WebGLBuffer objects are allocated, but the old ones are not deallocated, causing memory usage to grow indefinitely.

This issue is a regression, as it does not occur in version 8.9.2 but is present in subsequent versions. A reproducible example is provided below.

### Expected Behavior

Memory usage should remain stable when a PIXI.Graphics object is repeatedly cleared and redrawn.

### Steps to Reproduce

- Version 8.11.0 with memory leak is [here](https://www.pixiplayground.com/#/edit/6BYsJ99Aotqt55blcfhiS)
- Version 8.9.2 without memory leak is [here](https://www.pixiplayground.com/#/edit/7-ISVz7gGkQAaIZGlZiuG) 

1. Open the provided reproduction page and wait 10 seconds for the application to run and then destroy itself.
2. After it's destroyed, take a heap snapshot using your browser's developer tools.
3. When you filter the snapshot for WebGLBuffer, you will see that numerous buffer objects are still retained in memory.
4. Note the time logged in the console for the destroy operation. It is significantly slower (160ms vs. 3ms) because it gets stuck in WEBGL_lose_context.loseContext(). In our production app, this can cause the page to freeze for up to 30 seconds if it was open for the long time.

Heap snapshot with memory leak

Heap snapshot without leak

### Environment

- WebGL renderer 
- **`pixi.js` version**: *8.11.0*
- **Browser & Version**: *Chrome 138*
- **OS & Version**: *macOS 15.5*

### Possible Solution

_No response_

### Additional Information

_No response_

### LINKED ISSUE #11560: Bug: memory leak in safari
### Current Behavior

In the video:
- Below is Chrome, in Chrome, the memory is smooth.
- Above is Safari, in Safari, the memory is more and more.

https://github.com/user-attachments/assets/82da8f0e-eaea-4d81-b4bd-fa0582d2ce56

### Expected Behavior

Memory in Safari is smooth during multiple times dispose and init.

### Steps to Reproduce

codeSandBox: https://codesandbox.io/p/sandbox/jmgxk2?file=%2Fsprite.html%3A18%2C15
PreviewURL:  https://jmgxk2.csb.app/sprite.html

### Environment

- **`pixi.js` version**: *8.11*
- **Browser & Version**: *Safari*
- **OS & Version**: *MacOS 15.5 (24F74)*
- **Running Example**: *https://codesandbox.io/p/sandbox/jmgxk2?file=%2Fsprite.html%3A18%2C15*

### Possible Solution

_No response_

### Additional Information

_No response_

### LINKED ISSUE #11573: Bug: Memory Leak
### Current Behavior

Image

Image
Repeatedly creating and destroying sprites causes memory usage to continuously grow, indicating a potential memory leak.

### Expected Behavior

Memory status: Normal

### Steps to Reproduce

Memory status: Normal

### Environment

- **`pixi.js` version**: *e.g. 8.9.1*
- **Browser & Version**: *e.g. Chrome 108*
- **OS & Version**: *e.g. Ubuntu 22.04*
- **Running Example**: *e.g. <https://pixiplayground.com/>*

### Possible Solution

_No response_

### Additional Information

_No response_

### PR DESCRIPTION
**Pull request by Zyie**
Fixes: #11550 #11560 #11573

Addresses memory leaks by:

- Adding new `PoolCollector` singleton that allows us to register pools/caches that can be cleared up on destroy
- Adds new `fullCleanup` option to `renderer.destroy()`
- Adding destroy callbacks to various instruction pipes and systems to ensure proper resource cleanup.
- Clearing references to avoid circular dependencies and facilitate garbage collection.

I'm not sold on the naming of anything here so feel free to give some suggestions

### CODE REVIEW

**Comment by tsingwong** [comment]
> [pixi.js-base](https://pkg.pr.new/template/ad1dbbe4-196a-4df5-a818-54c846eae86a) • [pixi.js-bunny-mark](https://pkg.pr.new/template/5748dc5c-1353-4daa-be1d-059accc0952e)
> 
> ```
> npm i https://pkg.pr.new/pixijs/pixijs/pixi.js@11581
> ```
> 
> _commit: [`d87645c`](https://github.com/pixijs/pixijs/runs/46739855471)_


I just tried this version on Safari, but it still hasn't released the memory as Chrome.

**Comment by Zyie** [comment]
> I just tried this version on Safari, but it still hasn't released the memory as Chrome.

Safari does take a lot longer of a time to release the memory but after about 2 minutes it does release it from my testing. 
You may be also running into this issue: #11387

**Comment by VeselyT** [comment]
@Zyie Thank you for your prompt work on this matter #11550.

We tested the changes, and while they do resolve the memory leak upon destruction, our analysis indicates that the underlying buffer allocation issue from ticket #11550 remains.

Here are updated examples that better illustrate the issue. 

[Version 8.9.2 ](https://www.pixiplayground.com/#/edit/VW1vv3hw8DVkWeGpS-jtQ)
[This PR](https://stackblitz.com/edit/ahnorc5k?file=src%2Findex.js)

We've added number of gpu buffers currently allocated to the right top corner.  On the 8.9.2 the nunber is steady ~120, while code from this PR allocates more buffers until it reaches ~20k.

**Comment by Zyie** [comment]
> Here are updated examples that better illustrate the issue.

Thanks for the updated example, this is super helpful!

**Review by GoodBoyDigital — CHANGES_REQUESTED** [review]
Thanks for this @Zyie !

Was thinking PoolCollector as aconcept might work better as a `GlobalResourceRegistry ` that allows any global thing with a clear() function to be added. 

We could add any global resource to it and conceptually keeps it really simple! All we need is:

GlobalResourceRegistry.add(thingThatCanClear)

// later

`GlobalResourceRegistry.release()`

Rather than adding pipes to the destroy runners - we should itterate thgouth the pipes when destroy is called in abstract renderer and destroy them there - bit of an oversight that we never did that :P

File: src/utils/pool/Pool.ts [hunk 1]
```diff
@@ -106,6 +106,13 @@ export class Pool<T extends PoolItem>
...
     public clear()
     {
+        if (this._pool.length > 0 && this._pool[0].destroy)
+        {
+            for (let i = 0; i < this._index; i++)
+            {
+                this._pool[i].destroy();
+            }
+        }
         this._pool.length = 0;
```
Comment (afarber) [inline src/utils/pool/Pool.ts:116]: Isn't this missing here?

`this._pool._count = 0;`

**Review by bigtimebuddy — APPROVED** [review]

**Review by GoodBoyDigital — APPROVED** [review]

**Comment by codemonkeynorth** [comment]
I think this may be related:

> ISSUE: texture.destroy(true) on dynamic textures — BufferImageSource, BatchTextureArray, and ViewableBuffer still accumulate in renderPipes.batch

> DESCRIPTION: Pixi 8.18.x, dynamic BufferImageSource, batched drawing with filters. After sprites are detached and texture.destroy(true) is called, heap comparison still shows growth in BufferImageSource, BatchTextureArray, and ViewableBuffer until we manually sweep renderPipes.batch (clear batch texture slots and prune orphaned batchers). GC does not reclaim them — retainers point at batch pool and/or _batchersByInstructionSet. Long-lived Application, not a React unmount issue.

does that make any sense?

I had to write some manual cleanup routines (batch.textures.clear() etc)
