### PR TITLE
fix: allow mask to be null or undefined

### LINKED ISSUE #9953: Bug: 8.0.0-rc setting container mask to undefined results in typescript error
### Current Behavior

```
const container = new Container();
container.mask = undefined;
```

Gives this typescript error: Type 'undefined' is not assignable to type 'number | Container<View>'.

### Expected Behavior

Should not error

### Steps to Reproduce

Run typescript

### Environment

- **`pixi.js` version**: *e.g. 7.1.0*
- **Browser & Version**: *e.g. Chrome 108*
- **OS & Version**: *e.g. Ubuntu 22.04*
- **Running Example**: *e.g. <https://pixiplayground.com/>*

### Possible Solution

_No response_

### Additional Information

_No response_

### PR DESCRIPTION
**Pull request by Zyie**
fixes #9953

### CODE REVIEW

File: src/scene/container/container-mixins/effectsMixin.ts [hunk 1]
```diff
@@ -9,7 +9,7 @@ import type { Effect } from '../Effect';
 
 export interface EffectsMixinConstructor
 {
-    mask?: number | Container;
+    mask?: number | Container | null | undefined;
     filters?: Filter | Filter[];
```
Comment (bigtimebuddy) [inline src/scene/container/container-mixins/effectsMixin.ts:13]: While we are here, what about `filters`? Shouldn't that allow null/undefined as well?

**Review by bigtimebuddy — APPROVED** [review]

File: src/scene/container/container-mixins/effectsMixin.ts [hunk 2]
```diff
@@ -9,7 +9,7 @@ import type { Effect } from '../Effect';
 
 export interface EffectsMixinConstructor
 {
-    mask?: number | Container;
+    mask?: number | Container | null | undefined;
```
Comment (achamas-playco) [inline src/scene/container/container-mixins/effectsMixin.ts:12]: Being an optional type it implicitly accepts `undefined` so you just need to add `null`.
```suggestion
    mask?: number | Container | null;
```

**Review by achamas-playco — CHANGES_REQUESTED** [review]
Being an optional type it implicitly accepts `undefined` so you just need to add `null`.

**Review by achamas-playco — APPROVED** [review]
