### PR TITLE
Fix: padding issue on text

### LINKED ISSUE #10493: Bug: 8.1.0 Text texture is generated with the previous texture still partially visible
### Current Behavior

Text texture is rendered without fully clearing the previous canvas if padding is set.

### Expected Behavior

Text texture is generated on a cleared canvas

### Steps to Reproduce

- Add a Text with some padding set
- Update a style to change the text width (fontSize is the easiest but reproducible with wordWrapWidth etc.)
- Observe the text: texture is sometimes generated on a partailly cleared canvas and not a fully clear one

+1: Padding is not applied to the left and top sides, only on the bottom and right

### Environment

- **`pixi.js` version**: *8.1.0*
- **Browser & Version**: *Chrome 124.0.6367.92 (Official Build) (64-bit)*
- **OS & Version**: *Windows 11*
- **Running Example**: *[Playground](https://www.pixiplayground.com/#/edit/kPygYIZbVwghwcaLc6Tgt)*

### Possible Solution

_No response_

### Additional Information

_No response_

### PR DESCRIPTION
**Pull request by GoodBoyDigital**
##### Description of change
Fixes #10493 . When clearing the texture for reuse, I was not inclding the padding as part of the area that needed clearing. Easy fix at least!

##### Pre-Merge Checklist

- [x] Lint process passed (`npm run lint`)
- [x] Tests passed (`npm run test`)

### CODE REVIEW

**Review by bigtimebuddy — APPROVED** [review]

File: src/scene/text/canvas/CanvasTextSystem.ts [hunk 1]
```diff
@@ -161,7 +161,9 @@ export class CanvasTextSystem implements System
 
         context.scale(resolution, resolution);
 
-        context.clearRect(0, 0, measured.width + 4, measured.height + 4);
+        const padding = style.padding * 2;
+
+        context.clearRect(0, 0, measured.width + 4 + padding, measured.height + 4 + padding);
```
Comment (bigtimebuddy) [inline src/scene/text/canvas/CanvasTextSystem.ts:166]: Out of curiosity, why + 4?
