### PR TITLE
Fix: destroy and removeChild performance

### LINKED ISSUE #10345: Performance: [v8 regression] `Container.destroy()` is very slow on crowded containers
### Current Behavior

Admired developers,

I frequently have to clear crowded containers (>100000 children) and observed that `Container.destroy(true)` can take several seconds. 
Compared to my v7 code, where `destroy()` wasn't noticable at all (using `ParticleContainer`, to be fair).

Clearing the container 'by hand' before calling `destroy()` speeds up the process significantly, which makes me think it might be a bug.

```
myContainer.removeChildren().forEach(child => child.destroy(true));
``` 

### Expected Behavior

`destroy()` shouldn't be slower than clearing a `Container` by hand.

As fast as `ParticleContainer` would be great :).

### Steps to Reproduce

Use playground https://www.pixiplayground.com/#/edit/zFuIcJIth6M6QmC2IAjR9

After 200 frames, the content will be destroyed and starting to reconstruct. 
`largeContainer.destroy(true);` may halt rendering for a couple of seconds.

Setting `MAKE_IT_FAST_AGAIN=true` clears `largeContainer` manually before destruction, bringing up speed again, 

### Environment

- **`pixi.js` version**: 8.0.2
- **Browser & Version**: any
- **OS & Version**: any
- **Running Example**: https://www.pixiplayground.com/#/edit/zFuIcJIth6M6QmC2IAjR9

### Possible Solution

There is a workaround by clearing the container upfront `destroy()`:

```
myContainer.removeChildren().forEach(child => child.destroy(true));
```

### Additional Information

_No response_

### PR DESCRIPTION
**Pull request by GoodBoyDigital**
##### Description of change
The way rendergroup was being stored kind of bugged me as it was not as intuative as it could be. Consequentially, this meant its a bit harder to understand some of the checks that happen in the code around render groups.

Essentially the `renderGroup` property on `Container` could either be the Containers owned render group or its parent render group. Which is kind of weird!

I have modified this so we now have 
- `renderGroup` which is the the containers renderGroup created when `enableRenderGroup` is called
- `parentRenderGroup` a new property which is the render group that is responsible for rendering the container. this is set when a container is added to a rendergroup.

Modifications to RenderGroup
- i remove the `_children` property on renderGroup - we don't actually use it anywhere, so not point pushing and splicing it!
- added `getChildren` which will return them all should someone want to get the list of all renderables in a render group.
- tidied and streamlined some of the functionality of add / removing from a renderGroup to be a bit faster and easier to understand.
- I also added a removeChildren function to renderGroup.

Benchmark:
removeChildren / destroy is now 1000x faster in the demo from this issue: https://github.com/pixijs/pixijs/issues/10345

Will update a demo once a branch is built.

fixes #10345 and #10377

##### Pre-Merge Checklist

- [x] Tests and/or benchmarks are included
- [x] Documentation is changed or added
- [x] Lint process passed (`npm run lint`)
- [x] Tests passed (`npm run test`)

### CODE REVIEW

File: src/scene/container/container-mixins/effectsMixin.ts [hunk 1]
```diff
@@ -54,11 +54,18 @@ export const effectsMixin: Partial<Container> = {
...
         {
-            this.renderGroup.structureDidChange = true;
+            renderGroup.structureDidChange = true;
         }
 
+        // if (this.renderGroup)
+        // {
+        //     this.renderGroup.structureDidChange = true;
+        // }
+
```
Comment (Zyie) [inline src/scene/container/container-mixins/effectsMixin.ts:68]: remove?

File: tests/scene/scene.tests.ts [hunk 2]
```diff
@@ -202,15 +243,20 @@ describe('Scene', () =>
...
-        expect(container.renderGroup['_children']).toHaveLength(1);
-        expect(container2.renderGroup['_children']).toHaveLength(3);
+        expect(container.renderGroup.getChildren()).toHaveLength(1);
+        expect(container2.renderGroup.getChildren()).toHaveLength(3);
 
         expect(container.renderGroup).toEqual(container.renderGroup);
-        expect(container2.renderGroup).toEqual(container2.renderGroup);
-        expect(child.renderGroup).toEqual(container2.renderGroup);
+        expect(container2.parentRenderGroup).toEqual(container.renderGroup);
+        // expect(child.renderGroup).toEqual(container2.renderGroup);
```
Comment (Zyie) [inline tests/scene/scene.tests.ts:251]: is this meant to be commented out?

File: tests/scene/scene.tests.ts [hunk 3]
```diff
@@ -223,15 +269,15 @@ describe('Scene', () =>
...
-        expect(container.renderGroup['_children']).toHaveLength(2);
-        expect(container2.renderGroup['_children']).toHaveLength(2);
+        expect(container.renderGroup.getChildren()).toHaveLength(2);
+        expect(container2.renderGroup.getChildren()).toHaveLength(2);
 
         expect(container.renderGroup).toEqual(container.renderGroup);
-        expect(container2.renderGroup).toEqual(container2.renderGroup);
-        expect(child.renderGroup).toEqual(container2.renderGroup);
+        expect(container2.parentRenderGroup).toEqual(container.renderGroup);
+        // expect(child.renderGroup).toEqual(container2.renderGroup);
```
Comment (Zyie) [inline tests/scene/scene.tests.ts:277]: and this one

File: tests/scene/scene.tests.ts [hunk 4]
```diff
@@ -571,22 +574,15 @@ describe('Scene', () =>
...
 
         container.removeChild(container2);
 
-        expect(container.renderGroup.childrenToUpdate[1]).toEqual({
-            list: [child],
-            index: 1
-        });
+        compareUpdateList([child], container.renderGroup, 1);
+
+        expect(true).toBeTrue();
```
Comment (Zyie) [inline tests/scene/scene.tests.ts:585]: this seems wrong

File: tests/scene/scene.tests.ts [hunk 5]
```diff
@@ -502,27 +523,17 @@ describe('Scene', () =>
...
-        });
+        compareUpdateList([child], container.renderGroup, 1);
 
-        expect(container2.renderGroup.childrenToUpdate[1]).toEqual({
-            list: [child3],
-            index: 1
-        });
+        compareUpdateList([child3], container2.renderGroup, 1);
+
+        expect(true).toBeTrue();
```
Comment (Zyie) [inline tests/scene/scene.tests.ts:536]: this seems wrong

File: tests/scene/scene.tests.ts [hunk 6]
```diff
@@ -367,41 +412,21 @@ describe('Scene', () =>
...
-        });
+        compareUpdateList([child, container2], container.renderGroup, 1);
 
-        // child2.x = 50;
+        compareUpdateList([child2, child3], container.renderGroup, 2);
 
-        // expect(container.layerGroup.childrenToUpdate[2]).toEqual({
-        //     list: [child3, child2],
-        //     index: 2
+        expect(true).toBeTrue();
```
Comment (Zyie) [inline tests/scene/scene.tests.ts:429]: ?

File: tests/scene/scene.tests.ts [hunk 7]
```diff
@@ -446,24 +467,24 @@ describe('Scene', () =>
...
-        });
+        compareUpdateList([], container.renderGroup, 1);
 
-        expect(container2.renderGroup.childrenToUpdate[2]).toEqual({
-            list: [child],
-            index: 1
-        });
+        compareUpdateList([child], container2.renderGroup, 2);
+
+        expect(true).toBeTrue();
```
Comment (Zyie) [inline tests/scene/scene.tests.ts:474]: ?

File: tests/scene/scene.tests.ts (hunk 5 above)
Comment (GoodBoyDigital) [reply tests/scene/scene.tests.ts:536]: i know this looks a bit weird - its because the the lint rule specifies that there must be an expect function in the test. The expect is contained in the compareUpdateList function. I will disable the lint rule instead as that is a bit more reasonable!

File: tests/scene/scene.tests.ts (hunk 6 above)
Comment (GoodBoyDigital) [reply tests/scene/scene.tests.ts:429]: solved by disabling the lint rule

File: tests/scene/scene.tests.ts (hunk 7 above)
Comment (GoodBoyDigital) [reply tests/scene/scene.tests.ts:474]: solved by disabling the lint rule

File: tests/scene/scene.tests.ts (hunk 2 above)
Comment (GoodBoyDigital) [reply tests/scene/scene.tests.ts:251]: removed!

**Review by Zyie — APPROVED** [review]
