### PR TITLE
fix: worldAlpha becomes abnormal

### LINKED ISSUE #9600: Bug: when I call the getLocalBounds method, the value of worldAlpha becomes abnormal
### Current Behavior

```javascript
const container = new PIXI.Container();
container.alpha = 0.6;
app.stage.addChild(container);

const g = new PIXI.Graphics();
g.clear();
g.beginTextureFill({
  alpha: 1,
  color: 0xdd0000,
});
g.drawRect(0, 0, 100, 100);
g.endFill();
g.alpha = 0.4;
container.addChild(g);

app.ticker.add(() => {
  console.log(g.worldAlpha); // 0.24 right
  g.getLocalBounds();
  console.log(g.worldAlpha); // 0.4 wrong
});
```

### Expected Behavior

```javascript
const container = new PIXI.Container();
container.alpha = 0.6;
app.stage.addChild(container);

const g = new PIXI.Graphics();
g.clear();
g.beginTextureFill({
  alpha: 1,
  color: 0xdd0000,
});
g.drawRect(0, 0, 100, 100);
g.endFill();
g.alpha = 0.4;
container.addChild(g);

app.ticker.add(() => {
  console.log(g.worldAlpha); // 0.24
  g.getLocalBounds();
  console.log(g.worldAlpha); // 0.24
});
```

### Steps to Reproduce

When I call the getLocalBounds method, the value of worldAlpha becomes abnormal

### Environment

- PIXI version 7.1.0
- Chrome 108
- MacOs 13.2.1

### Possible Solution

_No response_

### Additional Information

_No response_

### PR DESCRIPTION
**Pull request by 372623460jh**
fix #9600.
when calling the `getLocalBounds` method, assign the parent node's `worldAlpha` value to `_tempDisplayObjectParent` so that the `updateTransform` method can correctly calculate the `worldAlpha`.

### CODE REVIEW

File: packages/display/src/DisplayObject.ts [hunk 1]
```diff
@@ -550,6 +550,8 @@ export abstract class DisplayObject extends utils.EventEmitter<DisplayObjectEven
         const parentRef = this.parent;
 
         this.parent = null;
+        // inherit the worldAlpha of the parent node
+        this._tempDisplayObjectParent.worldAlpha = parentRef?.worldAlpha || 1;
```
Comment (bigtimebuddy) [inline packages/display/src/DisplayObject.ts:554]: Minor suggestion to handle 0

```suggestion
        this._tempDisplayObjectParent.worldAlpha = parentRef?.worldAlpha ?? 1;
```

**Review by bigtimebuddy — APPROVED** [review]

**Comment by bigtimebuddy** [comment]
Thank you @372623460jh!
