### PR TITLE
Chore: Fix docs for WebGLOptions and WebGPUOptions

### LINKED ISSUE #10308: Bug: Some link in https://pixijs.download/v8.0.1/docs/rendering.AutoDetectOptions.html not working
### Current Behavior

WebGLOptions / WebGPUOptions option links are not working in this page
https://pixijs.download/v8.0.1/docs/rendering.AutoDetectOptions.html

One shows no options
https://pixijs.download/v8.0.1/docs/rendering.WebGLOptions.html

and the other one returns an error
https://pixijs.download/v8.0.1/docs/global.html#WebGPUOptions

<Error>
<Code>AccessDenied</Code>
<Message>Access Denied</Message>
<RequestId>2BT1Z6E52KCNZJ22</RequestId>
<HostId>GK/gfKByW8fnMYR4A89i4bt+gWfSKJ33PQWfOXTtohPztMia48m6+8AH1XSeilvIPLKM0J/JaJY=</HostId>
</Error>

### Expected Behavior

Links should work

### Steps to Reproduce

1) Goto https://pixijs.download/v8.0.1/docs/rendering.AutoDetectOptions.html
2) Click links for WebGLOptions
3) [webGLOptions are missing](https://cloud.videocom.com/media/fi_01HRPT3FHZPKFPEBG75M3K0EVE)
--------------------------------
1) Goto https://pixijs.download/v8.0.1/docs/rendering.AutoDetectOptions.html
2) Click link for WebGPUOptions
3) [Page has error](https://cloud.videocom.com/media/fi_01HRPT5BCPHMEPWEYSFGS6EJTJ)

### Environment

Win 11
Pixi v8.0.1
Chrome 122

### Possible Solution

_No response_

### Additional Information

_No response_

### PR DESCRIPTION
**Pull request by Zyie**
Fixes #10308

### CODE REVIEW

File: src/rendering/renderers/gl/context/GlContextSystem.ts [hunk 1]
```diff
@@ -8,30 +8,59 @@ import type { WebGLExtensions } from './WebGLExtensions';
 
 /**
  * Options for the context system.
- * @ignore
+ * @memberof rendering
+ * @property {WebGL2RenderingContext | null} [context=null] - User-provided WebGL rendering context object.
```
Comment (bigtimebuddy) [inline src/rendering/renderers/gl/context/GlContextSystem.ts:12]: Why are these docs duplicated below? Also I didn't think nested properties on interfaces required memberof.

Comment (Zyie) [reply src/rendering/renderers/gl/context/GlContextSystem.ts:12]: I couldn't figure out a better way to make an interface use `@memberof WebGLOptions` and also still be a member of the original interface

**Review by bigtimebuddy — APPROVED** [review]
