### PR TITLE
fix: render layer detachment when destroying.

### LINKED ISSUE #11373: Bug: Destroying parent which destroys children should also remove children from any render layers
### Current Behavior

When the parent is destroyed, resulting in children destroyed, we should also remove children from any render layers else we keep getting the warning

```
Container must be added to both layer and scene graph. Layers only handle render order - the scene graph is required for transforms (addChild) 
```

Not doing so will require keeping track of every transient child container which has been added to render layers and manually removing them from render layers

### Expected Behavior

Destroyed children should not give "Container must be added to both layer and scene graph. Layers only handle render order - the scene graph is required for transforms (addChild)" warning

### Steps to Reproduce

NA

### Environment

- **`pixi.js` version**: *8.9.1*

### Possible Solution

Currently i always have to do this

```typescript
destroy(options?: DestroyOptions): void {
    // Detach children from render layers (prevent stray warnings)
    for (const child of this.children) {
        child.parentRenderLayer.detach(child);
    }
}
```

### Additional Information

_No response_

### PR DESCRIPTION
**Pull request by GoodBoyDigital**
##### Description of change

Fix issue where when destroying a container - the children were not being removed from the render layers. 
Added test too.

fixes #11373 

##### Pre-Merge Checklist

- [x] Tests and/or benchmarks are included
- [x] Documentation is changed or added
- [x] Lint process passed (`npm run lint`)
- [x] Tests passed (`npm run test`)

### CODE REVIEW

File: src/scene/container/container-mixins/childrenHelperMixin.ts [hunk 1]
```diff
@@ -61,7 +61,14 @@ export const childrenHelperMixin: ChildrenHelperMixin<ContainerChild> = {
 
             for (let i = 0; i < removed.length; ++i)
             {
-                this.emit('childRemoved', removed[i], this, i);
+                const child = removed[i];
+
+                if (child.parentRenderLayer)
+                {
+                    child.parentRenderLayer.detach(child);
+                }
```
Comment (bigtimebuddy) [inline src/scene/container/container-mixins/childrenHelperMixin.ts:69]:
```suggestion
                child.parentRenderLayer?.detach(child);
```

**Review by bigtimebuddy — APPROVED** [review]
